# Generated by Django 4.2 on 2023-05-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bododataset_rename_dataset_assamesedataset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagset_language', models.CharField(blank=True, max_length=1000, null=True)),
                ('tagset_values', models.CharField(blank=True, max_length=1000, null=True)),
                ('tagset_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
