# Generated by Django 4.2 on 2023-06-05 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tagset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagset',
            name='tagset_language',
        ),
        migrations.AddField(
            model_name='metadata',
            name='tagset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tagset'),
        ),
        migrations.AddField(
            model_name='tagset',
            name='tagset_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Name of the Tagset'),
        ),
    ]
